Don't include "description" in "facts"
prometheus-msteams/prometheus-msteams pull request #157
Opened 2020-10-04 13:50 UTC by trallnag

https://github.com/prometheus-msteams/prometheus-msteams/issues/156

2020-10-06 09:35 UTC, Knappek commented
Thanks for the PR @trallnag. 
Please make sure to also adapt the tests such that they succeed and copy the template also over to the [charts default template please](https://github.com/prometheus-msteams/prometheus-msteams/blob/master/chart/prometheus-msteams/card.tmpl).

2020-10-06 19:00 UTC, trallnag commented
@Knappek, I think I'm done. I force pushed a rebase, that's why <https://github.com/prometheus-msteams/prometheus-msteams/pull/157#issuecomment-704463395> looks broken

2020-10-07 07:03 UTC, Knappek requested changes

2020-10-07 07:03 UTC, Knappek commented on pkg/card/testdata/action-message-card.tmpl
> +          {{- if eq $key "description" -}}
see comment above

2020-10-07 07:44 UTC, trallnag commented on default-message-card.tmpl
> +            {{- end -}}
Thanks for taking your time

2020-10-07 07:59 UTC, Knappek requested changes

2020-10-07 07:59 UTC, Knappek commented on chart/prometheus-msteams/Chart.yaml
> +version: 0.6.1
you don't need to bump this again. Please use `0.6.0`.

2020-10-07 08:01 UTC, Knappek commented on chart/prometheus-msteams/Chart.yaml
> +version: 0.6.1
Hang on...please don't change this version at all. I will create a new release and bump it, as `appVersion` will also change.

2020-10-07 08:05 UTC, Knappek approved these changes

2020-10-07 08:07 UTC, Knappek commented
Thanks again for this PR @trallnag . I will merge it.

2020-10-07 08:10 UTC, merged