Support authorization header
prometheus-msteams/prometheus-msteams pull request #269
Opened 2022-10-18 13:32 UTC by 0robustus1

This PR adds functionality to the `/_dynamicwebhook/` endpoint.

Currently the endpoint requires specifying the "Incoming Webhook" URL for MS Teams as part of the URL path.
The `receivers[].webhookConfigs[].url` is not considered a "secret"/"credential" field by Alertmanager in the same way as for example `receivers[].slackConfigs[].api_url` is. That means it won't be hidden from the config in the Web UI.

In order to support handling the Incoming Webhook URL like a secret credential we can rely on the `http_config` instead.
This PR adds support for specifying the Incoming Webhook URL in the `Authorization` header, with a bearer type of `webhook`.
Alertmanager will treat this as a credential and hide it from the Web UI.

2022-11-03 08:03 UTC, 0robustus1 commented
I have also added a small change to set the logger for retryablehttp in order for it to respect the `--debug=false` flag. It kept logging the webhook urls without it.

2023-04-18 08:05 UTC, 0robustus1 commented
Hi @kbudde, would you be up for taking a look at this pull-request?

2023-04-18 18:53 UTC, kbudde requested changes
LGTM to me, but please update pkg/service/logging.go to make the linter happy.

2023-04-18 18:59 UTC, kbudde commented
@0robustus1 I just merged #230. 
This is way simpler to supress the messages in debug=false mode. Can you just remove the levelLogger again, please.

2023-04-26 08:47 UTC, 0robustus1 commented
Done.

2023-04-26 20:33 UTC, kbudde approved these changes
Thank you

2023-04-26 20:34 UTC, merged